"""
Django settings for mydjango project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-hx-e$7jm!n3m+@=2gb#gc5-r++bss#pvi^(se3qmb1c6i2b-i-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
#ALLOWED_HOSTS = ['example.com', 'localhost:8000', '127.0.0.1','localhost']
#ALLOWED_HOSTS = ['localhost', '127.0.0.1']
SITE_ID=1
# Application definition
PORT = int(os.environ.get('PORT', 8000))
AUTHENTICATION_BACKENDS = [
    # ...
    'allauth.account.auth_backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]
INSTALLED_APPS = [
    'home.apps.HomeConfig',
    'vegie.apps.VegieConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',
    'allauth.socialaccount.providers.facebook',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

      'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'mydjango.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ os.path.join(BASE_DIR,"templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
            ],
        },
    },
]

WSGI_APPLICATION = 'mydjango.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# settings.py

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / "db.sqlite3",
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

#added manually

STATICFILES_DIRS = [
    os.path.join(BASE_DIR,"static")
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py

SOCIALACCOUNT_PROVIDERS = {
     
    'github': {
       'APP': {
           'client_id': 'fc294584160bd68bffc4',
            'secret': 'c10fad6293e935d907a9d77f71e1b5201fb5ad53',
           'key': '',
        }
    
    
     },

     'google': {
        'APP': {
            'client_id': '756753365871-30uhsqcsss829b8vsdbuj4h2ct52mt3v.apps.googleusercontent.com',
            'secret':'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',
            'key': '',
        }
}
,
'facebook': {
        
        'APP': {
            'client_id': '3585262148395989',
            'secret': '1015e7883bc267e579b8d7091ccd874b',
        },
    }
}

    


"""
SOCIALACCOUNT_PROVIDERS = {
   'google': {
        'APP': {
            'client_id': '756753365871-30uhsqcsss829b8vsdbuj4h2ct52mt3v.apps.googleusercontent.com',
            'secret':'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',
            'key': '',
        }
    'github': {
       'APP': {
           'client_id': ' b0023a425d4a56e7fbd7',
            'secret': '27dec034bb06837e4e742d392d4ecd56a1af8e34',
           'key': '',
        }
        
    }
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        #'OAUTH_PKCE_ENABLED': True,
    },
  }


  """




LOGIN_REDIRECT_URL='receipes'
#SOCIALACCOUNT_ADAPTER = 'your_project.your_app.adapters.CustomSocialAccountAdapter'


