# Generated by Django 4.2.7 on 2023-11-14 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_descprtion',
            new_name='recipe_description',
        ),
    ]
