# Generated by Django 4.2.7 on 2023-11-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegie', '0003_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
